import { Club, Player, Match, Referee, Stadium, VarCamera, Sanction } from "./types";

export const initialClubs: Club[] = [
  {
    id: "barcelona-sc",
    name: "Barcelona Sporting Club",
    shortName: "Barcelona S.C.",
    slug: "barcelona-sc",
    founded: "1925-05-01",
    city: "Guayaquil",
    stadium: "Estadio Monumental Banco Pichincha",
    status: "Habilitado",
    legalRepresentative: "Antonio Álvarez",
    contactEmail: "contacto@barcelonasc.com.ec",
    logo: "BSC",
    legalDocStatus: {
      estatutos: true,
      solvencia: true,
      ministerioDeporte: true,
      registroLigaPro: true,
    },
    squadCount: 7,
  },
  {
    id: "ldu-quito",
    name: "Liga Deportiva Universitaria",
    shortName: "L.D.U. Quito",
    slug: "ldu-quito",
    founded: "1918-10-23",
    city: "Quito",
    stadium: "Estadio Rodrigo Paz Delgado",
    status: "Habilitado",
    legalRepresentative: "Isaac Álvarez",
    contactEmail: "oficina@ldu.com.ec",
    logo: "LDU",
    legalDocStatus: {
      estatutos: true,
      solvencia: true,
      ministerioDeporte: true,
      registroLigaPro: true,
    },
    squadCount: 5,
  },
  {
    id: "ind-valle",
    name: "Independiente del Valle",
    shortName: "IDV",
    slug: "ind-valle",
    founded: "1958-03-01",
    city: "Sangolquí",
    stadium: "Estadio Banco Guayaquil",
    status: "Habilitado",
    legalRepresentative: "Franklin Tello",
    contactEmail: "contacto@idv.ec",
    logo: "IDV",
    legalDocStatus: {
      estatutos: true,
      solvencia: true,
      ministerioDeporte: true,
      registroLigaPro: true,
    },
    squadCount: 4,
  },
  {
    id: "emelec",
    name: "Club Sport Emelec",
    shortName: "C.S. Emelec",
    slug: "emelec",
    founded: "1929-04-28",
    city: "Guayaquil",
    stadium: "Estadio George Capwell",
    status: "Observado",
    legalRepresentative: "José Pileggi",
    contactEmail: "socios@emelec.com.ec",
    logo: "CSE",
    legalDocStatus: {
      estatutos: true,
      solvencia: false, // Observada solvencia económica
      ministerioDeporte: true,
      registroLigaPro: true,
    },
    squadCount: 4,
  },
  {
    id: "el-nacional",
    name: "Club Deportivo El Nacional",
    shortName: "El Nacional",
    slug: "el-nacional",
    founded: "1964-06-01",
    city: "Quito",
    stadium: "Estadio Olímpico Atahualpa",
    status: "Pendiente",
    legalRepresentative: "Marco Pazos",
    contactEmail: "directorio@elnacional.ec",
    logo: "ELN",
    legalDocStatus: {
      estatutos: true,
      solvencia: false,
      ministerioDeporte: false, // Firma del ministerio en revisión
      registroLigaPro: false,
    },
    squadCount: 3,
  },
  {
    id: "aucas",
    name: "Sociedad Deportiva Aucas",
    shortName: "S.D. Aucas",
    slug: "aucas",
    founded: "1945-02-06",
    city: "Quito",
    stadium: "Estadio Gonzalo Pozo Ripalda",
    status: "Habilitado",
    legalRepresentative: "Danny Walker",
    contactEmail: "comunicaciones@aucas.ec",
    logo: "SDA",
    legalDocStatus: {
      estatutos: true,
      solvencia: true,
      ministerioDeporte: true,
      registroLigaPro: true,
    },
    squadCount: 2,
  },
];

export const initialPlayers: Player[] = [
  // Barcelona SC Playel
  {
    id: "j-burrai",
    clubId: "barcelona-sc",
    name: "Javier Burrai",
    number: 1,
    position: "Arquero",
    nationality: "Argentino / Ecuatoriano",
    birthDate: "1990-11-23",
    status: "Habilitado",
    shirtNumber: 1,
    matchesPlayed: 11,
    yellowCards: 1,
    redCards: 0,
    goals: 0,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/176161.png&w=350&h=254",
    height: "1.88 m",
    weight: "83 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "l-sosa",
    clubId: "barcelona-sc",
    name: "Luca Sosa",
    number: 3,
    position: "Defensa",
    nationality: "Argentino / Ecuatoriano",
    birthDate: "1994-06-03",
    status: "Habilitado",
    shirtNumber: 3,
    matchesPlayed: 12,
    yellowCards: 2,
    redCards: 0,
    goals: 1,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/209930.png&w=350&h=254",
    height: "1.89 m",
    weight: "81 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "l-souza",
    clubId: "barcelona-sc",
    name: "Leonai Souza",
    number: 22,
    position: "Mediocampista",
    nationality: "Brasileño",
    birthDate: "1995-10-20",
    status: "Habilitado",
    shirtNumber: 22,
    matchesPlayed: 10,
    yellowCards: 4,
    redCards: 0,
    goals: 0,
    contractUntil: "2025-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/312153.png&w=350&h=254",
    height: "1.74 m",
    weight: "72 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "a-chala",
    clubId: "barcelona-sc",
    name: "Aníbal Chalá",
    number: 6,
    position: "Defensa",
    nationality: "Ecuatoriano",
    birthDate: "1996-05-09",
    status: "Habilitado",
    shirtNumber: 6,
    matchesPlayed: 11,
    yellowCards: 1,
    redCards: 0,
    goals: 0,
    contractUntil: "2025-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/181977.png&w=350&h=254",
    height: "1.78 m",
    weight: "74 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "d-diaz",
    clubId: "barcelona-sc",
    name: "Damián Díaz",
    number: 10,
    position: "Mediocampista",
    nationality: "Argentino / Ecuatoriano",
    birthDate: "1986-05-01",
    status: "Habilitado",
    shirtNumber: 10,
    matchesPlayed: 8,
    yellowCards: 1,
    redCards: 0,
    goals: 3,
    contractUntil: "2025-06",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/110825.png&w=350&h=254",
    height: "1.73 m",
    weight: "70 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "a-preciado",
    clubId: "barcelona-sc",
    name: "Adonis Preciado",
    number: 7,
    position: "Delantero",
    nationality: "Ecuatoriano",
    birthDate: "1997-05-15",
    status: "Suspendido",
    shirtNumber: 7,
    matchesPlayed: 9,
    yellowCards: 1,
    redCards: 1,
    goals: 2,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/297745.png&w=350&h=254",
    height: "1.78 m",
    weight: "73 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "j-corozo",
    clubId: "barcelona-sc",
    name: "Janner Corozo",
    number: 11,
    position: "Delantero",
    nationality: "Ecuatoriano",
    birthDate: "1995-09-08",
    status: "Habilitado",
    shirtNumber: 11,
    matchesPlayed: 11,
    yellowCards: 0,
    redCards: 0,
    goals: 4,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/219760.png&w=350&h=254",
    height: "1.75 m",
    weight: "69 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },

  // LDU Quito Players
  {
    id: "a-dominguez",
    clubId: "ldu-quito",
    name: "Alexander Domínguez",
    number: 22,
    position: "Arquero",
    nationality: "Ecuatoriano",
    birthDate: "1987-06-05",
    status: "Habilitado",
    shirtNumber: 22,
    matchesPlayed: 11,
    yellowCards: 1,
    redCards: 0,
    goals: 0,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/104597.png&w=350&h=254",
    height: "1.96 m",
    weight: "90 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "r-ade",
    clubId: "ldu-quito",
    name: "Ricardo Adé",
    number: 4,
    position: "Defensa",
    nationality: "Haitiano",
    birthDate: "1990-05-21",
    status: "Habilitado",
    shirtNumber: 4,
    matchesPlayed: 12,
    yellowCards: 2,
    redCards: 0,
    goals: 0,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/265819.png&w=350&h=254",
    height: "1.90 m",
    weight: "85 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "e-piovi",
    clubId: "ldu-quito",
    name: "Ezequiel Piovi",
    number: 5,
    position: "Mediocampista",
    nationality: "Argentino",
    birthDate: "1992-06-12",
    status: "Habilitado",
    shirtNumber: 5,
    matchesPlayed: 12,
    yellowCards: 3,
    redCards: 0,
    goals: 1,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/201211.png&w=350&h=254",
    height: "1.79 m",
    weight: "74 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "a-arce",
    clubId: "ldu-quito",
    name: "Alex Arce",
    number: 19,
    position: "Delantero",
    nationality: "Paraguayo",
    birthDate: "1995-06-16",
    status: "Habilitado",
    shirtNumber: 19,
    matchesPlayed: 12,
    yellowCards: 2,
    redCards: 0,
    goals: 12,
    contractUntil: "2027-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/275525.png&w=350&h=254",
    height: "1.87 m",
    weight: "82 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "j-julio",
    clubId: "ldu-quito",
    name: "Jhojan Julio",
    number: 10,
    position: "Mediocampista",
    nationality: "Ecuatoriano",
    birthDate: "1998-02-11",
    status: "Suspendido",
    shirtNumber: 10,
    matchesPlayed: 8,
    yellowCards: 5,
    redCards: 0,
    goals: 2,
    contractUntil: "2025-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/236511.png&w=350&h=254",
    height: "1.72 m",
    weight: "68 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "N/A",
    },
  },

  // IDV players
  {
    id: "m-ramirez",
    clubId: "ind-valle",
    name: "Moisés Ramírez",
    number: 1,
    position: "Arquero",
    nationality: "Ecuatoriano",
    birthDate: "2000-09-09",
    status: "Habilitado",
    shirtNumber: 1,
    matchesPlayed: 10,
    yellowCards: 0,
    redCards: 1,
    goals: 0,
    contractUntil: "2026-12",
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/268688.png&w=350&h=254",
    height: "1.86 m",
    weight: "82 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  },
  {
    id: "k-paez",
    clubId: "ind-valle",
    name: "Kendry Páez",
    number: 16,
    position: "Mediocampista",
    nationality: "Ecuatoriano",
    birthDate: "2007-05-04",
    status: "Habilitado",
    shirtNumber: 16,
    matchesPlayed: 11,
    yellowCards: 1,
    redCards: 0,
    goals: 4,
    contractUntil: "2025-06", // Then Chelsea FC
    image: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/350517.png&w=350&h=254",
    height: "1.77 m",
    weight: "71 kg",
    documentStatus: {
      photoId: true,
      contractSigned: true,
      medicalCertificate: true,
      transferCertificate: "Aprobado",
    },
  }
];

export const initialStadiums: Stadium[] = [
  {
    id: "monumental",
    name: "Estadio Monumental Banco Pichincha",
    city: "Guayaquil",
    altitude: 4,
    capacity: 57267,
    lightingLux: 1530,
    grassType: "Césped Natural",
    vorConnectivity: "Fibra Principal + Respaldo",
    locationCoords: { lat: -2.1862, lng: -79.9248 },
    varCertified: true,
    lastInspectionDate: "2026-04-15",
  },
  {
    id: "rodrigo-paz",
    name: "Estadio Rodrigo Paz Delgado",
    city: "Quito",
    altitude: 2850,
    capacity: 41575,
    lightingLux: 1480,
    grassType: "Césped Mixto",
    vorConnectivity: "Fibra Principal + Respaldo",
    locationCoords: { lat: -0.1077, lng: -78.4891 },
    varCertified: true,
    lastInspectionDate: "2026-04-20",
  },
  {
    id: "capwell",
    name: "Estadio George Capwell",
    city: "Guayaquil",
    altitude: 4,
    capacity: 40000,
    lightingLux: 1600,
    grassType: "Césped Natural",
    vorConnectivity: "Fibra Única",
    locationCoords: { lat: -2.2094, lng: -79.8930 },
    varCertified: true,
    lastInspectionDate: "2026-03-12",
  },
  {
    id: "banco-guayaquil",
    name: "Estadio Banco Guayaquil",
    city: "Sangolquí",
    altitude: 2500,
    capacity: 12000,
    lightingLux: 1200,
    grassType: "Césped Natural",
    vorConnectivity: "Fibra Principal + Respaldo",
    locationCoords: { lat: -0.3228, lng: -78.4375 },
    varCertified: true,
    lastInspectionDate: "2026-05-02",
  },
  {
    id: "atahualpa",
    name: "Estadio Olímpico Atahualpa",
    city: "Quito",
    altitude: 2780,
    capacity: 35258,
    lightingLux: 980,
    grassType: "Césped Natural",
    vorConnectivity: "Satelital",
    locationCoords: { lat: -0.1772, lng: -78.4764 },
    varCertified: false, // Observada por transmisión y luces lux bajas
    lastInspectionDate: "2026-05-10",
  },
];

export const initialReferees: Referee[] = [
  {
    id: "a-aragon",
    name: "Augusto Aragón",
    category: "FIFA",
    province: "Esmeraldas",
    matchesThisSeason: 14,
    activeConflicts: ["Emelec"], // Conflict constraints
  },
  {
    id: "g-guerrero",
    name: "Guillermo Guerrero",
    category: "FIFA",
    province: "Guayas",
    matchesThisSeason: 12,
    activeConflicts: ["Barcelona S.C.", "C.S. Emelec"],
  },
  {
    id: "f-congo",
    name: "Franklin Congo",
    category: "Nacional",
    province: "Imbabura",
    matchesThisSeason: 10,
    activeConflicts: [],
  },
  {
    id: "l-quiroz",
    name: "Luis Quiroz",
    category: "FIFA",
    province: "Azuay",
    matchesThisSeason: 11,
    activeConflicts: [],
  },
  {
    id: "a-cajas",
    name: "Álex Cajas",
    category: "Nacional",
    province: "Guayas",
    matchesThisSeason: 9,
    activeConflicts: ["Barcelona S.C."],
  },
];

export const initialSanctions: Sanction[] = [
  {
    id: "sanc-1",
    targetType: "Jugador",
    targetName: "Adonis Preciado",
    clubName: "Barcelona S.C.",
    offense: "Conducta violenta contra adversario (Falta grave)",
    severity: "Alta",
    fineUSD: 1500,
    matchesSuspended: 2,
    dateEmitted: "2026-05-18",
    resolved: false,
    appealDetails: {
      appellantComment: "El club argumenta que el jugador no tuvo intención de agredir, sino que fue producto de la inercia de la jugada.",
      appealDate: "2026-05-19",
      status: "Pendiente",
    },
  },
  {
    id: "sanc-2",
    targetType: "Jugador",
    targetName: "Jhojan Julio",
    clubName: "L.D.U. Quito",
    offense: "Acumulación de cinco tarjetas amarillas en el torneo",
    severity: "Baja",
    fineUSD: 500,
    matchesSuspended: 1,
    dateEmitted: "2026-05-17",
    resolved: true,
  },
  {
    id: "sanc-3",
    targetType: "Club",
    targetName: "Emelec",
    clubName: "C.S. Emelec",
    offense: "Uso indebido de pirotecnia no autorizada en graderíos por la hinchada",
    severity: "Media",
    fineUSD: 3000,
    matchesSuspended: 0,
    dateEmitted: "2026-05-12",
    resolved: true,
  },
  {
    id: "sanc-4",
    targetType: "Club",
    targetName: "El Nacional",
    clubName: "El Nacional",
    offense: "Retraso en el ingreso del equipo al terreno de juego (Segunda advertencia)",
    severity: "Baja",
    fineUSD: 1000,
    matchesSuspended: 0,
    dateEmitted: "2026-05-14",
    resolved: true,
  }
];

export const initialMatches: Match[] = [
  {
    id: "match-1",
    homeTeamId: "barcelona-sc",
    awayTeamId: "ldu-quito",
    date: "2026-05-24",
    time: "18:00",
    stadiumId: "monumental",
    status: "Programado",
    round: 12,
    tvChannel: "Zapping Sports",
    refereeAppointed: "Guillermo Guerrero",
    logistics: {
      seguridadOk: true,
      ambulanciaOk: true,
      transmisionTvOk: true,
      certificacionVarOk: true,
      balonerosOk: true,
    },
  },
  {
    id: "match-2",
    homeTeamId: "ind-valle",
    awayTeamId: "emelec",
    date: "2026-05-23",
    time: "15:30",
    stadiumId: "banco-guayaquil",
    status: "Programado",
    round: 12,
    tvChannel: "Zapping Sports",
    refereeAppointed: "Augusto Aragón",
    logistics: {
      seguridadOk: true,
      ambulanciaOk: true,
      transmisionTvOk: true,
      certificacionVarOk: true,
      balonerosOk: false, // Baloneros pendientes de acreditación
    },
  },
  {
    id: "match-3",
    homeTeamId: "aucas",
    awayTeamId: "el-nacional",
    date: "2026-05-24",
    time: "13:00",
    stadiumId: "atahualpa", // Atahualpa shared or Gonzalo Pozo
    status: "Programado",
    round: 12,
    tvChannel: "Zapping Sports",
    refereeAppointed: "Franklin Congo",
    logistics: {
      seguridadOk: false,
      ambulanciaOk: true,
      transmisionTvOk: false,
      certificacionVarOk: false,
      balonerosOk: true,
    },
  },
];

export const initialVarCameras: VarCamera[] = [
  { id: "cam-1", name: "Cámara 1 - Master Alta", angle: "Tiro Abierto Central", status: "Óptimo", lastVerified: "2026-05-22 14:00" },
  { id: "cam-2", name: "Cámara 2 - Master Táctica", angle: "Plano Medio Transmisión", status: "Óptimo", lastVerified: "2026-05-22 14:05" },
  { id: "cam-3", name: "Cámara 3 - Fuera de Juego Izquierda", angle: "Línea de 16.50 m Sur", status: "Óptimo", lastVerified: "2026-05-22 14:15" },
  { id: "cam-4", name: "Cámara 4 - Fuera de Juego Derecha", angle: "Línea de 16.50 m Norte", status: "Óptimo", lastVerified: "2026-05-22 14:20" },
  { id: "cam-5", name: "Cámara 5 - Arco Sur", angle: "Detrás de Portería Sur", status: "Falla de Calibración", lastVerified: "2026-05-22 15:30" },
  { id: "cam-6", name: "Cámara 6 - Arco Norte", angle: "Detrás de Portería Norte", status: "Óptimo", lastVerified: "2026-05-22 14:32" },
  { id: "cam-7", name: "Cámara 7 - Ultra Slow Motion", angle: "Detalle de faltas / VAR", status: "Óptimo", lastVerified: "2026-05-22 14:40" },
];
